#!/bin/sh
rm AbstractSymbol.java
rm AbstractTable.java
rm ASTConstants.java
rm ASTLexer.java
rm ASTParser.java
rm BoolConst.java
rm CgenSupport.java
rm cool-tree.aps
rm Flags.java
rm IdSymbol.java
rm IdTable.java
rm IntSymbol.java
rm IntTable.java
rm ListNode.java
rm Makefile
rm Semant.java
rm StringSymbol.java
rm StringTable.java
rm SymbolTable.java
rm SymtabExample.java
rm TokenConstants.java
rm TreeNode.java
rm Utilities.java
cp /usr/class/cs143/cool/src/PA4J/AbstractSymbol.java .
cp /usr/class/cs143/cool/src/PA4J/AbstractTable.java .
cp /usr/class/cs143/cool/src/PA4J/ASTConstants.java .
cp /usr/class/cs143/cool/src/PA4J/ASTLexer.java .
cp /usr/class/cs143/cool/src/PA4J/ASTParser.java .
cp /usr/class/cs143/cool/src/PA4J/BoolConst.java .
cp /usr/class/cs143/cool/src/PA4J/CgenSupport.java .
cp /usr/class/cs143/cool/src/PA4J/cool-tree.aps .
cp /usr/class/cs143/cool/src/PA4J/Flags.java .
cp /usr/class/cs143/cool/src/PA4J/IdSymbol.java .
cp /usr/class/cs143/cool/src/PA4J/IdTable.java .
cp /usr/class/cs143/cool/src/PA4J/IntSymbol.java .
cp /usr/class/cs143/cool/src/PA4J/IntTable.java .
cp /usr/class/cs143/cool/src/PA4J/ListNode.java .
cp /usr/class/cs143/cool/etc/../assignments/PA4J/Makefile .
cp /usr/class/cs143/cool/src/PA4J/Semant.java .
cp /usr/class/cs143/cool/src/PA4J/StringSymbol.java .
cp /usr/class/cs143/cool/src/PA4J/StringTable.java .
cp /usr/class/cs143/cool/src/PA4J/SymbolTable.java .
cp /usr/class/cs143/cool/src/PA4J/SymtabExample.java .
cp /usr/class/cs143/cool/src/PA4J/TokenConstants.java .
cp /usr/class/cs143/cool/src/PA4J/TreeNode.java .
cp /usr/class/cs143/cool/src/PA4J/Utilities.java .
